rwisheaders = {
    'sensor_data' : [['station','id','string'],
                     
                     ['timestamp:utc','sec','epoch time'],
                     ['timestamp:local','sec','epoch'],
                     ['timestamp:localstring','time','time string'],
                     ['timestamp_raw','time','time string'],
                     
                     ['essAtmosphericPressure','in*Hg','float'],
                     ['essAtmosphericPressure_raw','0.1*mb','int'],
                     
                     ['essAvgWindDirection','deg','float'],
                     ['essAvgWindDirection_raw','deg','int'],
                     ['essAvgWindSpeed','mph','float'],
                     ['essAvgWindSpeed_raw','0.1*m/s','int'],
                     ['essSpotWindDirection','deg','float'],
                     ['essSpotWindDirection_raw','deg','int'],
                     ['essSpotWindSpeed','mph','float'],
                     ['essSpotWindSpeed_raw','0.1*m/s','int'],
                     ['essMaxWindGustSpeed','mph','float'],
                     ['essMaxWindGustSpeed_raw','0.1*m/s','int'],
                     ['essMaxWindGustDir','deg','float'],
                     ['essMaxWindGustDir_raw','deg','int'],
                     
                     ['essAirTemperature.1','deg F','float'],
                     ['essAirTemperature.1_raw','0.1*C','int'],
                     ['essWetbulbTemp','deg F','float'],
                     ['essWetbulbTemp_raw','0.1*C','int'],
                     ['essDewpointTemp','deg F','float'],
                     ['essDewpointTemp_raw','0.1*C','int'],
                     ['essMaxTemp','deg F','float'],
                     ['essMaxTemp_raw','0.1*C','int'],
                     ['essMinTemp','deg F','float'],
                     ['essMinTemp_raw','0.1*C','int'],
                     
                     ['essRelativeHumidity','%','float'],
                     ['essRelativeHumidity_raw','%','int'],
                     
                     ['essPrecipYesNo','enum','string'],
                     ['essPrecipYesNo_raw','enum','int'],
                     ['essPrecipRate','in/hr','float'],
                     ['essPrecipRate_raw','0.1*kg/m^2/s','int'],
                     ['essPrecipSituation','enum','string'],
                     ['essPrecipSituation_raw','enum','int'],
                     
                     ['essPrecipitationStartTime:utc','sec','epoch time'],
                     ['essPrecipitationStartTime:local','sec','epoch time'],
                     ['essPrecipitationStartTime:localstring','local','time string'],
                     ['essPrecipitationStartTime_raw','sec','epoch time'],
                     
                     ['essPrecipitationEndTime:utc','sec','epoch time'],
                     ['essPrecipitationEndTime:local','sec','epoch time'],
                     ['essPrecipitationEndTime:localstring','local','time string'],
                     ['essPrecipitationEndTime_raw','sec','epoch time'],

                     #-- note: 0.1*kg/m^2 is approx 0.1*mm for rainfall
                     ['essPrecipitationOneHour','in','float'],
                     ['essPrecipitationOneHour_raw','0.1*kg/m^2','int'],
                     ['essPrecipitationThreeHours','in','float'],
                     ['essPrecipitationThreeHours_raw','0.1*kg/m^2','int'],
                     ['essPrecipitationSixHours','in','float'],
                     ['essPrecipitationSixHours_raw','0.1*kg/m^2','int'],
                     ['essPrecipitationTwelveHours','in','float'],
                     ['essPrecipitationTwelveHours_raw','0.1*kg/m^2','int'],
                     ['essPrecipitation24Hours','in','float'],
                     ['essPrecipitation24Hours_raw','0.1*kg/m^2','int'],
                     
                     ['essVisibility','mi','float'],
                     ['essVisibility_raw','0.1*m','int'],
                     ['essVisibilitySituation','enum','string'],
                     ['essVisibilitySituation_raw','enum','int'],
                     
                     ['essPavementSensorIndex.1','index','int'],
                     ['essPavementSensorIndex.1_raw','index','int'],
                     ['essPavementSensorIndex.2','index','int'],
                     ['essPavementSensorIndex.2_raw','index','int'],
                     ['essPavementSensorIndex.3','index','int'],
                     ['essPavementSensorIndex.3_raw','index','int'],
                     ['essPavementSensorIndex.4','index','int'],
                     ['essPavementSensorIndex.4_raw','index','int'],
                     ['essPavementSensorIndex.5','index','int'],
                     ['essPavementSensorIndex.5_raw','index','int'],
                     ['essPavementSensorIndex.6','index','int'],
                     ['essPavementSensorIndex.6_raw','index','int'],
                     ['essPavementSensorIndex.7','index','int'],
                     ['essPavementSensorIndex.7_raw','index','int'],
                     ['essPavementSensorIndex.8','index','int'],
                     ['essPavementSensorIndex.8_raw','index','int'],
                     
                     ['essPavementType.1','enum','string'],
                     ['essPavementType.1_raw','enum','int'],
                     ['essPavementType.2','enum','string'],
                     ['essPavementType.2_raw','enum','int'],
                     ['essPavementType.3','enum','string'],
                     ['essPavementType.3_raw','enum','int'],
                     ['essPavementType.4','enum','string'],
                     ['essPavementType.4_raw','enum','int'],
                     ['essPavementType.5','enum','string'],
                     ['essPavementType.5_raw','enum','int'],
                     ['essPavementType.6','enum','string'],
                     ['essPavementType.6_raw','enum','int'],
                     ['essPavementType.7','enum','string'],
                     ['essPavementType.7_raw','enum','int'],
                     ['essPavementType.8','enum','string'],
                     ['essPavementType.8_raw','enum','int'],
                     
                     ['essPavementSensorType.1','enum','string'],
                     ['essPavementSensorType.1_raw','enum','int'],
                     ['essPavementSensorType.2','enum','string'],
                     ['essPavementSensorType.2_raw','enum','int'],
                     ['essPavementSensorType.3','enum','string'],
                     ['essPavementSensorType.3_raw','enum','int'],
                     ['essPavementSensorType.4','enum','string'],
                     ['essPavementSensorType.4_raw','enum','int'],
                     ['essPavementSensorType.5','enum','string'],
                     ['essPavementSensorType.5_raw','enum','int'],
                     ['essPavementSensorType.6','enum','string'],
                     ['essPavementSensorType.6_raw','enum','int'],
                     ['essPavementSensorType.7','enum','string'],
                     ['essPavementSensorType.7_raw','enum','int'],
                     ['essPavementSensorType.8','enum','string'],
                     ['essPavementSensorType.8_raw','enum','int'],
                     
                     ['essSurfaceStatus.1','enum','string'],
                     ['essSurfaceStatus.1_raw','enum','int'],       
                     ['essSurfaceStatus.2','enum','string'],
                     ['essSurfaceStatus.2_raw','enum','int'],
                     ['essSurfaceStatus.3','enum','string'],
                     ['essSurfaceStatus.3_raw','enum','int'],
                     ['essSurfaceStatus.4','enum','string'],
                     ['essSurfaceStatus.4_raw','enum','int'],
                     ['essSurfaceStatus.5','enum','string'],
                     ['essSurfaceStatus.5_raw','enum','int'],
                     ['essSurfaceStatus.6','enum','string'],
                     ['essSurfaceStatus.6_raw','enum','int'],
                     ['essSurfaceStatus.7','enum','string'],
                     ['essSurfaceStatus.7_raw','enum','int'],
                     ['essSurfaceStatus.8','enum','string'],
                     ['essSurfaceStatus.8_raw','enum','int'],
                     
                     ['essSurfaceTemperature.1','deg F','float'],
                     ['essSurfaceTemperature.1_raw','',''],
                     ['essSurfaceTemperature.2','deg F','float'],
                     ['essSurfaceTemperature.2_raw','',''],
                     ['essSurfaceTemperature.3','deg F','float'],
                     ['essSurfaceTemperature.3_raw','',''],
                     ['essSurfaceTemperature.4','deg F','float'],
                     ['essSurfaceTemperature.4_raw','',''],
                     ['essSurfaceTemperature.5','deg F','float'],
                     ['essSurfaceTemperature.5_raw','',''],
                     ['essSurfaceTemperature.6','deg F','float'],
                     ['essSurfaceTemperature.6_raw','',''],
                     ['essSurfaceTemperature.7','deg F','float'],
                     ['essSurfaceTemperature.7_raw','',''],
                     ['essSurfaceTemperature.8','deg F','float'],
                     ['essSurfaceTemperature.8_raw','',''],
                     
                     ['essPavementTemperature.1','deg F','float'],
                     ['essPavementTemperature.1_raw','0.1*C','int'],
                     ['essPavementTemperature.2','deg F','float'],
                     ['essPavementTemperature.2_raw','0.1*C','int'],
                     ['essPavementTemperature.3','deg F','float'],
                     ['essPavementTemperature.3_raw','0.1*C','int'],
                     ['essPavementTemperature.4','deg F','float'],
                     ['essPavementTemperature.4_raw','0.1*C','int'],
                     ['essPavementTemperature.5','deg F','float'],
                     ['essPavementTemperature.5_raw','0.1*C','int'],
                     ['essPavementTemperature.6','deg F','float'],
                     ['essPavementTemperature.6_raw','0.1*C','int'],
                     ['essPavementTemperature.7','deg F','float'],
                     ['essPavementTemperature.7_raw','0.1*C','int'],
                     ['essPavementTemperature.8','deg F','float'],
                     ['essPavementTemperature.8_raw','0.1*C','int'],
                     
                     ['essSurfaceIceOrWaterDepth.1','in','float'],
                     ['essSurfaceIceOrWaterDepth.1_raw','mm','int'],
                     ['essSurfaceIceOrWaterDepth.2','in','float'],
                     ['essSurfaceIceOrWaterDepth.2_raw','mm','int'],
                     ['essSurfaceIceOrWaterDepth.3','in','float'],
                     ['essSurfaceIceOrWaterDepth.3_raw','','int'],
                     ['essSurfaceIceOrWaterDepth.4','in','float'],
                     ['essSurfaceIceOrWaterDepth.4_raw','mm','int'],
                     ['essSurfaceIceOrWaterDepth.5','in','float'],
                     ['essSurfaceIceOrWaterDepth.5_raw','mm','int'],
                     ['essSurfaceIceOrWaterDepth.6','in','float'],
                     ['essSurfaceIceOrWaterDepth.6_raw','mm',''],
                     ['essSurfaceIceOrWaterDepth.7','in','float'],
                     ['essSurfaceIceOrWaterDepth.7_raw','mm','int'],
                     ['essSurfaceIceOrWaterDepth.8','in','float'],
                     ['essSurfaceIceOrWaterDepth.8_raw','mm','int'],
                     
                     ['essSurfaceSalinity.1','pp100K','float'],
                     ['essSurfaceSalinity.1_raw','pp100K','int'],
                     ['essSurfaceSalinity.2','pp100K','float'],
                     ['essSurfaceSalinity.2_raw','pp100K','int'],
                     ['essSurfaceSalinity.3','pp100K','float'],
                     ['essSurfaceSalinity.3_raw','pp100K','int'],
                     ['essSurfaceSalinity.4','pp100K','float'],
                     ['essSurfaceSalinity.4_raw','pp100K','int'],
                     ['essSurfaceSalinity.5','pp100K','float'],
                     ['essSurfaceSalinity.5_raw','pp100K','int'],
                     ['essSurfaceSalinity.6','pp100K','float'],
                     ['essSurfaceSalinity.6_raw','pp100K','int'],
                     ['essSurfaceSalinity.7','pp100K','float'],
                     ['essSurfaceSalinity.7_raw','pp100K','int'],
                     ['essSurfaceSalinity.8','pp100K','float'],
                     ['essSurfaceSalinity.8_raw','pp100K','int'],
                     
                     ['essSurfaceFreezePoint.1','deg F','float'],
                     ['essSurfaceFreezePoint.1_raw','0.1*C','int'],
                     ['essSurfaceFreezePoint.2','deg F','float'],
                     ['essSurfaceFreezePoint.2_raw','0.1*C','int'],
                     ['essSurfaceFreezePoint.3','deg F','float'],
                     ['essSurfaceFreezePoint.3_raw','0.1*C','int'],
                     ['essSurfaceFreezePoint.4','deg F','float'],
                     ['essSurfaceFreezePoint.4_raw','0.1*C','int'],
                     ['essSurfaceFreezePoint.5','deg F','float'],
                     ['essSurfaceFreezePoint.5_raw','0.1*C','int'],
                     ['essSurfaceFreezePoint.6','deg F','float'],
                     ['essSurfaceFreezePoint.6_raw','0.1*C','int'],
                     ['essSurfaceFreezePoint.7','deg F','float'],
                     ['essSurfaceFreezePoint.7_raw','0.1*C','int'],
                     ['essSurfaceFreezePoint.8','deg F','float'],
                     ['essSurfaceFreezePoint.8_raw','0.1*C','int'],
                     
                     ['essSurfaceBlackIceSignal.1','enum','string'],
                     ['essSurfaceBlackIceSignal.1_raw','enum','int'],
                     ['essSurfaceBlackIceSignal.2','enum','string'],
                     ['essSurfaceBlackIceSignal.2_raw','enum','int'],
                     ['essSurfaceBlackIceSignal.3','enum','string'],
                     ['essSurfaceBlackIceSignal.3_raw','enum','int'],
                     ['essSurfaceBlackIceSignal.4','enum','string'],
                     ['essSurfaceBlackIceSignal.4_raw','enum','int'],
                     ['essSurfaceBlackIceSignal.5','enum','string'],
                     ['essSurfaceBlackIceSignal.5_raw','enum','int'],
                     ['essSurfaceBlackIceSignal.6','enum','string'],
                     ['essSurfaceBlackIceSignal.6_raw','enum','int'],
                     ['essSurfaceBlackIceSignal.7','enum','string'],
                     ['essSurfaceBlackIceSignal.7_raw','enum','int'],
                     ['essSurfaceBlackIceSignal.8','enum','string'],
                     ['essSurfaceBlackIceSignal.8_raw','enum','int'],
                     
                     ['essSubSurfaceSensorIndex.1','index','int'],
                     ['essSubSurfaceSensorIndex.1_raw','index','int'],
                     ['essSubSurfaceSensorIndex.2','index','int'],
                     ['essSubSurfaceSensorIndex.2_raw','index','int'],
                     ['essSubSurfaceSensorIndex.3','index','int'],
                     ['essSubSurfaceSensorIndex.3_raw','index','int'],
                     ['essSubSurfaceSensorIndex.4','index','int'],
                     ['essSubSurfaceSensorIndex.4_raw','index','int'],
                     ['essSubSurfaceSensorIndex.5','index','int'],
                     ['essSubSurfaceSensorIndex.5_raw','index','int'],
                     ['essSubSurfaceSensorIndex.6','index','int'],
                     ['essSubSurfaceSensorIndex.6_raw','index','int'],
                     ['essSubSurfaceSensorIndex.7','index','int'],
                     ['essSubSurfaceSensorIndex.7_raw','index','int'],
                     ['essSubSurfaceSensorIndex.8','index','int'],
                     ['essSubSurfaceSensorIndex.8_raw','index','int'],
                     
                     ['essSubSurfaceType.1','enum','string'],
                     ['essSubSurfaceType.1_raw','enum','int'],
                     ['essSubSurfaceType.2','enum','string'],
                     ['essSubSurfaceType.2_raw','enum','int'],
                     ['essSubSurfaceType.3','enum','string'],
                     ['essSubSurfaceType.3_raw','enum','int'],
                     ['essSubSurfaceType.4','enum','string'],
                     ['essSubSurfaceType.4_raw','enum','int'],
                     ['essSubSurfaceType.5','enum','string'],
                     ['essSubSurfaceType.5_raw','enum','int'],
                     ['essSubSurfaceType.6','enum','string'],
                     ['essSubSurfaceType.6_raw','enum','int'],
                     ['essSubSurfaceType.7','enum','string'],
                     ['essSubSurfaceType.7_raw','enum','int'],
                     ['essSubSurfaceType.8','enum','string'],
                     ['essSubSurfaceType.8_raw','enum','int'],
                     
                     ['essSubSurfaceDepth.1','in','float'],
                     ['essSubSurfaceDepth.1_raw','cm','int'],
                     ['essSubSurfaceDepth.2','in','float'],
                     ['essSubSurfaceDepth.2_raw','cm','int'],
                     ['essSubSurfaceDepth.3','in','float'],
                     ['essSubSurfaceDepth.3_raw','cm','int'],
                     ['essSubSurfaceDepth.4','in','float'],
                     ['essSubSurfaceDepth.4_raw','cm','int'],
                     ['essSubSurfaceDepth.5','in','float'],
                     ['essSubSurfaceDepth.5_raw','cm','int'],
                     ['essSubSurfaceDepth.6','in','float'],
                     ['essSubSurfaceDepth.6_raw','cm','int'],
                     ['essSubSurfaceDepth.7','in','float'],
                     ['essSubSurfaceDepth.7_raw','cm','int'],
                     ['essSubSurfaceDepth.8','in','float'],
                     ['essSubSurfaceDepth.8_raw','cm','int'],
                     
                     ['essSubSurfaceTemperature.1','deg F','float'],
                     ['essSubSurfaceTemperature.1_raw','0.1*C','int'],
                     ['essSubSurfaceTemperature.2','deg F','float'],
                     ['essSubSurfaceTemperature.2_raw','0.1*C','int'],
                     ['essSubSurfaceTemperature.3','deg F','float'],
                     ['essSubSurfaceTemperature.3_raw','0.1*C','int'],
                     ['essSubSurfaceTemperature.4','deg F','float'],
                     ['essSubSurfaceTemperature.4_raw','0.1*C','int'],
                     ['essSubSurfaceTemperature.5','deg F','float'],
                     ['essSubSurfaceTemperature.5_raw','0.1*C','int'],
                     ['essSubSurfaceTemperature.6','deg F','float'],
                     ['essSubSurfaceTemperature.6_raw','0.1*C','int'],
                     ['essSubSurfaceTemperature.7','deg F','float'],
                     ['essSubSurfaceTemperature.7_raw','0.1*C','int'],
                     ['essSubSurfaceTemperature.8','deg F','float'],
                     ['essSubSurfaceTemperature.8_raw','0.1*C','int']
                     ],
    'metadata' : [['station','id','string'],
                  ['timestamp:utc','sec','epoch time'],
                  ['timestamp:local','sec','epoch time'],
                  ['timestamp:localstring','time','time string'],
                  ['district','none','int'],
                  ['locationName','none','text'],
                  ['nearbyPlace','none','text'],
                  ['longitude','deg','float'],
                  ['latitude','deg','float'],
                  ['elevation','ft','float'],
                  ['direction','none','text'],
                  ['county','none','text'],
                  ['route','none','text'],
                  ['routeSuffix','none','text'],
                  ['postmilePrefix','none','text'],
                  ['alignment','none','text'],
                  ['milepost','mi','float'],
                  ['inService','none','bool'],
                  ['essReferenceHeight','ft','float'],
                  ['essPressureHeight','ft','float'],
                  ['essWindSensorHeight','ft','float'],
                  ['essNumTemperatureSensors','none','int'],
                  ['numEssPavementSensors','none','int'],
                  ['numEssSubSurfaceSensors','none','int'],
                  ['alert','none','bool'],
                  ['alertAppliesTo','none','text'],
                  ['qc_pass','none','bool']
                  ],
    }
